### ISSUE TITLE
solar neutron activator not working in daylight dimension

### ISSUE THREAD

**Issue by RetroZivo** [Dunkmania101/DaylightDimension#1] opened 2021-01-23 13:46 UTC
problem is in the title
its is not converting into polonium

**Comment by Dunkmania101** [comment] 2021-01-23 13:55
Now that's weird! And also kind of funny and ironic, given that's kind of the whole reason I made the mod :)

I'll see what I can do.

**Comment by Dunkmania101** [comment] 2021-01-23 15:28
Well, I can confirm it seems to happen to me too, although I have no idea why. I think the allthemodium mining dimension might work, although I'm not sure. I'm pretty sure it's always day there, just not about whether the machines work there. It turns out rain is no longer a concern because they changed it so that they just slow down, rather than stopping. You might be able to resort to that while I try to figure this one out.

**Comment by RetroZivo** [comment] 2021-01-24 00:49
i am using 1.16.4 if that's relevant

**Comment by RetroZivo** [comment] 2021-01-24 00:50
> Well, I can confirm it seems to happen to me too, although I have no idea why. I think the allthemodium mining dimension might work, although I'm not sure. I'm pretty sure it's always day there, just not about whether the machines work there. It turns out rain is no longer a concern because they changed it so that they just slow down, rather than stopping. You might be able to resort to that while I try to figure this one out.

I saw a issue reported like this in ATM 6 github page

**Comment by Dunkmania101** [comment] 2021-01-25 15:42
I figured I should mention that I found the cause, it was the fixed time part. I'm having trouble getting it to stay at noon without defining that in the json file since that makes forge tell Mekanism it's not daytime.

**Comment by Dunkmania101** [comment] 2021-01-25 15:44
I suppose I also saw that the same issue exists with the ATM mining dimension for the same reason so that alternative won't work for now. I did let them know about it, though.

**Comment by Dunkmania101** [comment] 2021-02-13 18:40
It looks like Mekanism fixed it in 1.16.5-10.0.20.447. I'll close this for now, feel free to reopen if needed.

**Closed as completed by Dunkmania101** 2021-02-13 18:40 UTC
